# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift👷🏻' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift👷🏻
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'

  target 'RxSwift👷🏻Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift👷🏻UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
